#!/usr/bin/env bash
# One-time conversion: copy your real rofi theme and fastfetch config into
# templates/ and replace the hardcoded palette values with {{tokens}}.
#
# Done with sed on a copy of YOUR files (never retyped), so Nerd Font glyphs
# and any edits you made are preserved byte-for-byte. Your originals are not
# modified. Needs GNU sed (the I flag).
#
#   ./make-templates.sh                               # default ~/.config paths
#   ./make-templates.sh path/to/nothing.rasi path/to/config.jsonc
#
# Afterwards:  ./apply_theme.py --diff   and read what it would change.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROFI_SRC="${1:-$HOME/.config/rofi/nothing.rasi}"
FF_SRC="${2:-$HOME/.config/fastfetch/config.jsonc}"
ROFI_TMPL="$HERE/templates/rofi-nothing.rasi.tmpl"
FF_TMPL="$HERE/templates/fastfetch.jsonc.tmpl"

for f in "$ROFI_SRC" "$FF_SRC"; do
  [[ -f "$f" ]] || { echo "error: $f not found" >&2; exit 1; }
done
for f in "$ROFI_TMPL" "$FF_TMPL"; do
  [[ ! -e "$f" ]] || { echo "error: $f already exists; delete it first if you want to redo the conversion" >&2; exit 1; }
done
mkdir -p "$HERE/templates"

cp -L "$ROFI_SRC" "$ROFI_TMPL"
sed -E -i \
  -e '1i /* AUTO-GENERATED by apply_theme.py - edit the template in theme-switcher, not this file. */' \
  -e '/Nothing OS tokens/,/source of truth instead\. \*\//c\    /* Colors below come from palette.json via apply_theme.py. */' \
  -e 's/#e2201f88/{{accent|hasha:88}}/Ig' \
  -e 's/#1b1c1d/{{background|hash}}/Ig' \
  -e 's/#232425/{{surface|hash}}/Ig' \
  -e 's/#fdfdfd/{{foreground|hash}}/Ig' \
  -e 's/#e2201f/{{accent|hash}}/Ig' \
  -e 's/rgba\(245, 240, 240, 0\.55\)/{{muted|hash}}/g' \
  -e 's/rgba\(226, 32, 31, 0\.35\)/{{accent|css:0.35}}/g' \
  "$ROFI_TMPL"

cp -L "$FF_SRC" "$FF_TMPL"
sed -E -i \
  -e '1s|^.*$|// AUTO-GENERATED by apply_theme.py - edit the template in theme-switcher, not this file.|' \
  -e '/^\/\/ Tokens:/d' \
  -e 's/#e2201f/{{accent|hash}}/Ig' \
  -e 's/#fdfdfd/{{foreground|hash}}/Ig' \
  -e 's/38;2;226;32;31/38;2;{{accent|ansi}}/g' \
  "$FF_TMPL"

echo "wrote $ROFI_TMPL"
echo "wrote $FF_TMPL"

# Anything still hardcoded is a spot the accent will NOT follow.
left="$(grep -nEi '#1b1c1d|#232425|#fdfdfd|#e2201f|226, ?32, ?31|226;32;31|245, ?240, ?240' "$ROFI_TMPL" "$FF_TMPL" || true)"
if [[ -n "$left" ]]; then
  echo
  echo "WARNING: palette values still hardcoded in the templates; convert these by hand:" >&2
  echo "$left" >&2
fi
echo
echo "Next: ./apply_theme.py --diff"
